import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Create demo user
  const hashedPassword = await bcrypt.hash("demo1234!", 12);
  const user = await prisma.user.upsert({
    where: { email: "demo@rapid.dev" },
    update: {},
    create: {
      name: "Demo User",
      email: "demo@rapid.dev",
      password: hashedPassword,
      role: "USER",
      subscription: {
        create: {
          plan: "PRO",
          status: "ACTIVE",
        },
      },
    },
  });

  console.log("Created demo user:", user.email);

  // Create sample analysis
  const analysis = await prisma.analysis.upsert({
    where: { id: "demo-analysis-1" },
    update: {},
    create: {
      id: "demo-analysis-1",
      userId: user.id,
      title: "payment-service.ts",
      type: "CODE",
      status: "COMPLETED",
      language: "TypeScript",
      costSavings: 1240,
      reliabilityScore: 72,
      performanceScore: 68,
      rawContent: `// Payment Service\nexport async function processPayment(userId: string, amount: number) {\n  const user = await db.query('SELECT * FROM users WHERE id = ' + userId);\n  // Process payment...\n}`,
      suggestions: {
        create: [
          {
            title: "Replace SELECT * with specific columns",
            description: "Selecting only needed columns reduces data transfer by 60-80%, saving ~$300/month in bandwidth and DB costs.",
            category: "COST_SAVING",
            priority: "HIGH",
            estimatedSaving: 300,
            estimatedEffort: "1-2 hours",
            status: "PENDING",
          },
          {
            title: "Fix SQL injection vulnerability",
            description: "User input is directly concatenated into SQL query. Use parameterized queries immediately.",
            category: "SECURITY",
            priority: "CRITICAL",
            estimatedSaving: 0,
            estimatedEffort: "30 minutes",
            status: "PENDING",
          },
          {
            title: "Add database connection pooling",
            description: "Connection pooling reduces overhead by 80% and improves response times significantly.",
            category: "PERFORMANCE",
            priority: "HIGH",
            estimatedSaving: 200,
            estimatedEffort: "2-4 hours",
            status: "PENDING",
          },
        ],
      },
    },
  });

  console.log("Created sample analysis:", analysis.id);

  // Create sample document
  await prisma.document.upsert({
    where: { id: "demo-doc-1" },
    update: {},
    create: {
      id: "demo-doc-1",
      userId: user.id,
      analysisId: analysis.id,
      title: "Analysis Report: payment-service.ts",
      type: "TECHNICAL",
      content: `# Analysis Report: payment-service.ts

## Overview
- **Language**: TypeScript
- **Analysis Type**: CODE
- **Date**: March 31, 2026
- **Reliability Score**: 72/100
- **Performance Score**: 68/100

## Key Findings

### Cost Savings Opportunity
Estimated potential savings: **$1,240/month**

### Suggestions Summary
1. **Replace SELECT * with specific columns** (HIGH priority) - COST SAVING
2. **Fix SQL injection vulnerability** (CRITICAL priority) - SECURITY
3. **Add database connection pooling** (HIGH priority) - PERFORMANCE

## Recommendations
Review each suggestion in the Suggestions tab and approve implementations as needed.

---
*Generated by RAPID - Read, Analyze, Patch, Implement & Document*`,
    },
  });

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
