import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getRequestUser } from "@/lib/request-auth";
import { calculateScores, detectLanguage, generateFindings, type AnalyzeInputType } from "@/lib/analysis";
import { z } from "zod";

const analyzeSchema = z.object({
  title: z.string().min(1).max(200),
  content: z.string().min(1),
  type: z.enum(["CODE", "DATABASE", "DASHBOARD", "API", "INFRASTRUCTURE", "GENERAL"]),
  fileName: z.string().optional(),
});

export async function POST(req: NextRequest) {
  try {
    const user = await getRequestUser(req);
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { title, content, type, fileName } = analyzeSchema.parse(body);

    const language = detectLanguage(content, fileName);
    const suggestions = generateFindings(content, language, type as AnalyzeInputType);
    const { reliabilityScore, performanceScore } = calculateScores(content, suggestions);

    // Save to DB
    const analysis = await prisma.analysis.create({
      data: {
        userId: user.id,
        title,
        type: type as any,
        status: "COMPLETED",
        language,
        rawContent: content.substring(0, 10000), // Store first 10k chars
        fileName,
        fileSize: content.length,
        costSavings: null,
        reliabilityScore,
        performanceScore,
        analysisResult: {
          language,
          findingsCount: suggestions.length,
          analyzedAt: new Date().toISOString(),
          authMethod: user.authMethod,
        },
        suggestions: {
          create: suggestions.map((s) => ({
            title: s.title,
            description: s.description,
            category: s.category as any,
            priority: s.priority as any,
            estimatedSaving: null,
            estimatedEffort: s.estimatedEffort,
            codeSnippet: s.codeSnippet,
            improvedCode: s.improvedCode,
            status: "PENDING",
          })),
        },
      },
      include: { suggestions: true },
    });

    // Auto-generate documentation
    await prisma.document.create({
      data: {
        userId: user.id,
        analysisId: analysis.id,
        title: `Analysis Report: ${title}`,
        type: "TECHNICAL",
        content: `# Analysis Report: ${title}

## Overview
- **Language**: ${language}
- **Analysis Type**: ${type}
- **Date**: ${new Date().toLocaleDateString()}
- **Reliability Score**: ${reliabilityScore}/100
- **Performance Score**: ${performanceScore}/100

## Key Findings

### Findings Summary
${suggestions.map((s, i) => `${i + 1}. **${s.title}** (${s.priority} priority) - ${s.category.replace("_", " ")}`).join("\n")}

## Next Steps
Review the findings, capture any code changes you want to make, and update your implementation notes as needed.

---
*Generated by RAPID - Read, Analyze, Patch, Implement & Document*`,
      },
    });

    return NextResponse.json({
      analysis: {
        id: analysis.id,
        title: analysis.title,
        language,
        type,
        reliabilityScore,
        performanceScore,
        findingsCount: suggestions.length,
      },
      suggestions,
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.errors[0].message }, { status: 400 });
    }
    console.error("Analysis error:", error);
    return NextResponse.json({ error: "Analysis failed" }, { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  const user = await getRequestUser(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const analyses = await prisma.analysis.findMany({
    where: { userId: user.id },
    orderBy: { createdAt: "desc" },
    include: {
      suggestions: { select: { id: true, status: true, category: true, priority: true, estimatedSaving: true } },
    },
  });

  return NextResponse.json(analyses);
}
